vim.cmd "imap <expr> <C-l>   vsnip#available(1)  ? '<Plug>(vsnip-expand-or-jump)' : '<C-l>'"
vim.cmd "smap <expr> <C-l>   vsnip#available(1)  ? '<Plug>(vsnip-expand-or-jump)' : '<C-l>'"
vim.cmd "imap <expr> <C-j>   vsnip#available(1)  ? '<Plug>(vsnip-jump-next)' : '<C-j>'"
vim.cmd "smap <expr> <C-j>   vsnip#available(1)  ? '<Plug>(vsnip-jump-next)' : '<C-j>'"
vim.cmd "imap <expr> <C-k>   vsnip#available(1)  ? '<Plug>(vsnip-jump-prev)' : '<C-k>'"
vim.cmd "smap <expr> <C-k>   vsnip#available(1)  ? '<Plug>(vsnip-jump-prev)' : '<C-k>'"
